### PR TITLE
Publishing post about side projects

### PR DESCRIPTION
**Pull request by basicallydan**
Looking for feedback on style, content, grammar, spelling. Is my reasoning sound? Is my message clear? Is my spelling correct?

EDIT: Can be viewed at http://dev.danhough.com/blog/side-projects/

### CODE REVIEW

**Comment by M-Zuber** [comment]
Message seems clear.
I have a similar Trello board and may just follow your lead :)

You might want to also check out http://beta.hemingwayapp.com/ for more feedback on readability

**Comment by basicallydan** [comment]
Thanks @M-Zuber! I'll have a go with hemingway. Let me know if you do that with your Trello board ;)

**Comment by M-Zuber** [comment]
:+1:
Definitely looks nicer now

**Comment by basicallydan** [comment]
Thanks!

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Pull request merged**
